In [1]:
%load_ext cython

In [2]:
%%cython --annotate
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
#distutils: extra_compile_args = -fopenmp
#distutils: extra_link_args = -fopenmp
# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: nonecheck=False
# cython: cdivision=True
cimport cython
import cython
cimport numpy as np
import numpy as np
np.import_array()


cdef class unixtime:
    
    cdef np.ndarray values
    
    def __cinit__(unixtime self, np.ndarray[np.int_t, ndim=1] values):
        self.values = values
    
    cpdef years(unixtime self):
        return self.values // 31556952

    

    




    # def __repr__(self):
    #     return f"timeseries({self.dt})"

dt = np.array(["1970-01-01T00:00:00.000000000", "1970-01-01T00:00:01.000000000"], dtype=np.datetime64)
ts = unixtime(dt.astype('int64'))
print(ts.years())

[ 0 31]


In [3]:
import numpy as np
# np.array(["1970-01-01T00:00:00.000000000", "1970-01-01T00:00:01.000000000"], dtype=np.datetime64).astype("datetime64[Y]").astype(np.int64) + 1970
from typing import Self
from typing import NamedTuple

import nzthermo as nzt

values = np.array([
    "1970-01-01T00:00:00.000000000",
    # a leap year
    "2020-02-29T00:00:00.000000000",
    "2024-02-29T00:00:01.000000000",
    "2024-02-29",
    
    
], dtype="datetime64[ns]")

a = nzt.timeseries(values)
    
print(
f"""
{a}
years  {a.years}
months {a.months}
days   {a.days}
hours  {a.hours}
delta_t {a.delta_t}
{np.array(a)}
{a.to_datetime64()}
"""
)

def degrees(x: float) -> float:
    return x * 180 / np.pi

def radians(x: float) -> float:
    return x * np.pi / 180

np.testing.assert_almost_equal(degrees(radians(1)), 1)

np.deg2rad(1) == radians(1), np.rad2deg(1) == degrees(1)



Timeseries(years=array([1970, 2020, 2024, 2024], dtype=uint32), months=array([1, 2, 2, 2], dtype=uint32), days=array([ 1, 29, 29, 29], dtype=uint32), hours=array([0, 0, 0, 0], dtype=uint32), minutes=array([0, 0, 0, 0], dtype=uint32), seconds=array([0, 0, 1, 0], dtype=uint32), microseconds=array([0, 0, 0, 0], dtype=uint32))
years  [1970 2020 2024 2024]
months [1 2 2 2]
days   [ 1 29 29 29]
hours  [0 0 0 0]
delta_t [40.23467888 71.66730358 73.94523658 73.94523658]
[[1970 2020 2024 2024]
 [   1    2    2    2]
 [   1   29   29   29]
 [   0    0    0    0]
 [   0    0    0    0]
 [   0    0    1    0]
 [   0    0    0    0]]
['1970-01-01T00:00:00.000000' '2020-02-29T00:00:00.000000'
 '2024-02-29T00:00:01.000000' '2024-02-29T00:00:00.000000']



(True, True)

In [9]:
import datetime
nzt.timeseries(datetime.datetime.now().timestamp())

1716201353.765075